name: app_boilerplate
description: "Production-ready Flutter starter: clean architecture, BLoC, Dio, Firebase."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  bloc: ^9.2.1
  flutter_bloc: ^9.1.1
  equatable: ^3.0.0

  # Dependency Injection
  get_it: ^9.3.0

  # HTTP Client
  dio: ^5.11.1

  # Storage
  shared_preferences: ^2.5.6
  flutter_secure_storage: ^11.2.0

  # Firebase
  firebase_core: ^4.15.0
  firebase_messaging: ^16.7.0
  firebase_analytics: ^12.6.0

  # Local Notifications
  flutter_local_notifications: ^22.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.5

flutter:
  uses-material-design: true
